---
# tasks file for zero_footprint_qbittorrent_seedbox/07-reboot

- name: REBOOT | 7.1 Enable all required services
  ansible.builtin.systemd:
    state: "stopped"
    enabled: true
    daemon_reload: true
    name: "{{ item }}"
  become: true
  loop: "{{ required_services }}"
  tags:
    - reboot

- name: REBOOT | 7.2 Reboot a machine
  ansible.builtin.reboot:
    reboot_timeout: "{{ reboot_timeout }}"
  become: true
  when: require_reboot
  tags:
    - reboot

- name: REBOOT | 7.3 Test we can logon back after the reboot
  ansible.builtin.ping:
  tags:
    - reboot
