---
# .github/workflows/ansible-lint.yml
name: ansible-lint
on:   # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main", "stable", "release/v*", "feature/*", "bugfix/*"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Run ansible-lint"
        uses: ansible/ansible-lint@main
        with:
          args: "-v"
          setup_python: "true"
          working_directory: ""
          requirements_file: "requirements.yml"
